// Automatically generated by MockGen. DO NOT EDIT!
// Source: /development/go-workspace/src/github.com/tkashem/fizbus/export_test.go

package fizbus

import (
	gomock "github.com/golang/mock/gomock"
)

// Mock of canceller interface
type Mockcanceller struct {
	ctrl     *gomock.Controller
	recorder *_MockcancellerRecorder
}

// Recorder for Mockcanceller (not exported)
type _MockcancellerRecorder struct {
	mock *Mockcanceller
}

func NewMockcanceller(ctrl *gomock.Controller) *Mockcanceller {
	mock := &Mockcanceller{ctrl: ctrl}
	mock.recorder = &_MockcancellerRecorder{mock}
	return mock
}

func (_m *Mockcanceller) EXPECT() *_MockcancellerRecorder {
	return _m.recorder
}

func (_m *Mockcanceller) Cancel() {
	_m.ctrl.Call(_m, "Cancel")
}

func (_mr *_MockcancellerRecorder) Cancel() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Cancel")
}
